# 配置ffmpeg的执行
ffmpeg: ffmpeg

# 配置口袋48执行的一些配置
pocket48:
  # 直播
  live:
    # 自动录制的成员名字或ID，必须是字符串
    recordName: [
      '马欣宇',
      '郑照暄',
      '95552277',
      '95552291'
    ]
    # 下载视频的目录
    downloadDir: '.download_dir/live'
  # 录播
  video:
    # 下载视频的目录
    downloadDir: '.download_dir/video'