# 配置ffmpeg的执行
ffmpeg: ffmpeg

# 配置口袋48执行的一些配置
pocket48:
  # 直播
  live:
    # 自动录制的成员名字或ID
    recordName: []
    # 下载视频的目录
    downloadDir: '.download_dir/live'
  # 录播
  download:
    # 下载视频的目录
    downloadDir: '.download_dir/download'